environment_configs:
- seed: 41
data_configs:
- on_disk_shard_root: /lustre/groups/ml01/workspace/olga.novitskaia/lpm_style/.plib_cache/plibdata_multiout/lpm_multiout_all_data_plus_tahoe_novartis_op3_molholdout_h100_2x_bs4096_200epoch_lustre
  on_disk_data_sources:
  - cigs_mce_CVCL_0062
  - cigs_mce_CVCL_0063
  val_and_test_perturbations_selected_from: all
  cache_shards_in_memory: true
  data_storage_type: on_disk
  on_disk_split_annotation_path: /ictstr01/groups/ml01/workspace/artur.szalata/code/chem-perturbridge_lpm/results/cross_dataset_molecule_holdout_split_all_data_plus_tahoe_novartis_op3/df_annot_split.parquet
model_configs:
- model_id: LPM
  model_args:
    optimizer_name: AdamW
    learning_rate: 0.002
    learning_rate_decay: 0.97
    num_layers: 2
    hidden_dim: 256
    dropout: 0.1
    batch_size: 4096
    embedding_dim: 128
    output_mode: multiout
    num_workers: 4
    epoch_checkpoint_every_n: 0
    epoch_checkpoint_save_last: false
    resume_from_checkpoint: null
    lightning_trainer_pars:
      deterministic: true
      enable_checkpointing: true
      accelerator: gpu
      devices: 2
      num_nodes: 1
      strategy: ddp
      use_distributed_sampler: true
      num_sanity_val_steps: 0
      max_epochs: 200
    keep_best_validation_checkpoint: true
    pretrained_perturbation_embeddings_path: /ictstr01/groups/ml01/workspace/artur.szalata/code/chem-perturbridge_lpm/.plib_cache/morgan_perturbation_embeddings/pubchem_morgan_radius2_nbits128/compound_embeddings.npy
    freeze_pretrained_perturbation_embeddings: true
  save_model_after_training: false
  wandb_config:
    enabled: true
    required: true
    project: chem-perturbridge-lpm
    name: lpm_paper10_morgan_fixed_scratch_cigs_mce_seed41_molholdout_h100_2x_bs4096_200epoch_lustre
    group: lpm_paper10_morgan_fixed_molholdout_h100_bs4096_200epoch_lustre
    tags:
    - lpm
    - multiout
    - paper10
    - single-dataset
    - scratch
    - frozen-morgan-fingerprints
    - molecule-holdout
    - cigs_mce
    - seed-41
    - h100-2x
    - bs4096
    log_model: false
    config:
      paper10_stage: scratch_target_only_frozen_morgan
      single_dataset: CIGS MCE
      single_dataset_slug: cigs_mce
      seed: 41
      morgan_radius: 2
      morgan_nbits: 128
      pretrained_perturbation_embeddings_path: /ictstr01/groups/ml01/workspace/artur.szalata/code/chem-perturbridge_lpm/.plib_cache/morgan_perturbation_embeddings/pubchem_morgan_radius2_nbits128/compound_embeddings.npy
      freeze_pretrained_perturbation_embeddings: true
